#
# lua Travis-CI Hook
#

# Travis language: c(sharp) :-P
language: csharp

sudo: required

before_install:
 - date -u
 - uname -a
 - export PATH=/opt/mono/bin:$PATH
 - env | sort

install: ./CI/travis.${TRAVIS_OS_NAME}.install.deps.sh

script:
  - git submodule update --init --recursive
  - ./run_all.linux64.sh

# Execute additional tests or commands
#after_script:
#  - [run additional test commans]

# Only watch the master branch
branches:
  only:
    - master
    - /^lua-.*$/

# Notify if needed
notifications:
  recipients:
    - viniciusjarina@gmail.com
  email:
    on_success: change
    on_failure: always